// Code generated by GoPlay Protocol Extension Generator. DO NOT EDIT.
using System;
using System.Threading.Tasks;
using GoPlay.Services.Core.Protocols;
using Common.Protocols;

namespace GoPlay.Services.Extension.Frontend
{
    public static class ProtocolConsts
    {
        //Protocols
        public const string Login_Login = "login.login";
        public const string Echo_Request = "echo.request";
        public const string Echo_PushAll = "echo.push.all";
        
        //Pushes
        public const string Push_LoginNewUser = "login.new.user";
        public const string Push_EchoPush = "echo.push";
    }

    public static class ClientExtensions
    {
        public static Task<(Status, LoginResponse)> Login_Login(this Client cli, LoginRequest arg)
        {
            return cli.Request<LoginRequest, LoginResponse>(ProtocolConsts.Login_Login, arg);
        }

        public static Task<(Status, PbString)> Echo_Request(this Client cli, PbString arg)
        {
            return cli.Request<PbString, PbString>(ProtocolConsts.Echo_Request, arg);
        }

        public static void Echo_PushAll(this Client cli, PbString arg)
        {
            cli.Notify(ProtocolConsts.Echo_PushAll, arg);
        }

        
    }
}